spring.application.name=inventarios
#conexion mysql
spring.datasource.url=jdbc:mysql://localhost:3306/GouPets_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Configurar el patron del log
logging.pattern.console= [%thread] %-5level: %logger - %msg%n
# Configurar el nivel de Log
logging.level=INFO
# Cambiar puerto de TOMCAT
# server.port=8080
spring.main.banner-mode=off